---
- name: install lamp
  hosts: all
  become: true
  tasks:
    - name: install lamp
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql
