---
- name: install lamp
  hosts: all
  become: true
  tasks:
    - name: install lamp
      apt:
        name: "{{ item }}"
        update_cache: true
        state: present
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql
    - name: copy info.php to /var/www/html
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted    