---
#  this is the yaml to install apache2
- name: installation of apache2
  hosts: all
  become: true
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
# this yaml start the apache service        
    - name: start apache2 service
      systemd:
        name: apache2
        state: started
  