---
- name: Install LAMP
  hosts: all
  become: true
  tasks:
    - name: Install LAMP packages
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Copy info.php to /var/www/html
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html
      notify: restart apache2

  handlers:
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted
